# Generated by Django 2.2.12 on 2021-08-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=11)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookstore.Book')),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
