# Generated by Django 2.2.12 on 2021-08-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
