# Generated by Django 2.2.12 on 2021-08-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_auto_20210822_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True, verbose_name='bookname')),
                ('pub', models.CharField(default='', max_length=100, verbose_name='pub')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='price')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='market')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
            },
        ),
    ]
