# Generated by Django 2.2.12 on 2021-08-31 08:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='username')),
                ('nickname', models.CharField(max_length=30, verbose_name='nickname')),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('sign', models.CharField(default=user.models.default_sign, max_length=50, verbose_name='')),
                ('info', models.CharField(default='', max_length=150, verbose_name='')),
                ('sex', models.IntegerField(choices=[(0, 'woman'), (1, 'man')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
