# Generated by Django 2.2.12 on 2021-09-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
