# Generated by Django 2.2.12 on 2021-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tec', '技术'), ('game', '游戏'), ('news', '新闻'), ('sports', '体育')], default='tec', max_length=11),
        ),
    ]
