# Generated by Django 2.2.12 on 2021-09-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210903_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
